version: '3.2'
services:

  redis:
    image: redis:5.0.3
    volumes:
      - type: bind
        source: ./redis.conf
        target: /data/redis.conf
    command: redis-server redis.conf

  servo:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - OPTUNE_ACCOUNT=${ACCOUNT}
    volumes:
      - type: bind
        source: ./secret.yaml
        target: /servo/secret.yaml
        read_only: true
      - type: bind
        source: ./optune.token
        target: /servo/optune.token
    command: --auth-token optune.token redis-demo